version: '3.9'
name: 'webcrawler'

services:
  crawler:
    build: ./crawler
    volumes:
      - ./crawler:/crawler
    restart: on-failure
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  
  web:
    build: ./web
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - ./web:/web
    depends_on:
      - db
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  pma:
    image: phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    volumes:
      - ./pma:/pma
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql:latest
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "${DB_PORT_HOST}:3306"
    restart: on-failure
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}